[workspace]
members = [
    "cli",
    "."
]
default-members = [
    "."
]

[workspace.package]
version = "0.12.0-alpha.1"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://rgb.tech"
repository = "https://github.com/RGB-WG/rgb"
rust-version = "1.77.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.8.0"
strict_encoding = "2.8.1"
commit_verify = "0.12.0-beta.1"
nonasync = "0.1.2"
hypersonic = "0.12.0-beta.1"
bp-std = { version = "0.12.0-alpha.1", features = ["client-side-validation"] }
bp-electrum = "0.12.0-beta.1"
bp-esplora = { version = "0.12.0-beta.1", default-features = false }
bp-wallet = { version = "0.12.0-beta.1" }
rgb-std = { version = "0.12.0-alpha.1" }
# rgb-psbt = { version = "0.11.0-beta.9", path = "psbt" }
rgb-bp = { version = "0.12.0-alpha.1", path = "." }
indexmap = "2.7.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[package]
name = "rgb-bp"
version.workspace = true
description = "RGB smart contracts wallet runtime"
keywords.workspace = true
categories.workspace = true
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rgbp"
crate-type = ["cdylib", "rlib"]

[dependencies]
amplify = { workspace = true }
hypersonic = { workspace = true }
commit_verify = { workspace = true }
nonasync = { workspace = true }
bp-std = { workspace = true }
bp-electrum = { workspace = true, optional = true }
bp-esplora = { workspace = true, optional = true }
bp-wallet = { workspace = true }
rgb-std = { workspace = true, features = ["bitcoin"] }
#rgb-psbt = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
all = [
    "std",
    #"esplora_blocking", "electrum_blocking", "mempool_blocking",
    "serde", "log", "fs",
    #"cli"
]
std = []
fs = [
    "std",
    "serde",
    "rgb-std/fs",
    "bp-wallet/fs",
]
#cli = ["fs", "bp-wallet/cli"]
#esplora_blocking = ["bp-esplora", "bp-esplora/blocking"]
#esplora_blocking-wasm = ["bp-esplora", "bp-esplora/blocking-wasm"]
#electrum_blocking = ["bp-electrum"]
#mempool_blocking = ["esplora_blocking"]
serde = [
    "dep:serde", "serde_yaml",
    "bp-std/serde", "rgb-std/serde"
]

[package.metadata.docs.rs]
features = ["all"]

[patch.crates-io]
ultrasonic = { git = "https://github.com/AluVM/ultrasonic" }
hypersonic = { git = "https://github.com/AluVM/sonic" }
single_use_seals = { git = "https://github.com/LNP-BP/client_side_validation", branch = "v0.12" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "v0.12" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "v0.12" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "v0.12" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "v0.12" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "v0.12" }
bp-derive = { git = "https://github.com/BP-WG/bp-std", branch = "v0.12" }
descriptors = { git = "https://github.com/BP-WG/bp-std", branch = "v0.12" }
psbt = { git = "https://github.com/BP-WG/bp-std", branch = "v0.12" }
bp-std = { git = "https://github.com/BP-WG/bp-std", branch = "v0.12" }
bp-electrum = { git = "https://github.com/BP-WG/bp-electrum-client", branch = "v0.12" }
bp-esplora = { git = "https://github.com/BP-WG/bp-esplora-client", branch = "v0.12" }
bp-wallet = { git = "https://github.com/BP-WG/bp-wallet", branch = "v0.12" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "v0.12" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.12" }
