[workspace]
members = [".", "psbt", "cli"]
default-members = [".", "psbt"]

[workspace.package]
version = "0.12.0-beta.4"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://rgb.tech"
repository = "https://github.com/RGB-WG/rgb"
rust-version = "1.77.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.8.0"
nonasync = "0.1.2"
strict_encoding = "2.8.1"
commit_verify = "=0.12.0-beta.4"
bp-std = { version = "=0.12.0-beta.4", features = ["client-side-validation"] }
bp-electrum = "=0.12.0-beta.4"
bp-esplora = { version = "=0.12.0-beta.4", default-features = false }
bp-wallet = { version = "=0.12.0-beta.4" }
rgb-std = { version = "=0.12.0-beta.4" }
rgb-runtime = { version = "=0.12.0-beta.4", path = "." }
rgb-psbt = { version = "=0.12.0-beta.4", path = "psbt" }
indexmap = "2.7.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[package]
name = "rgb-runtime"
description = "RGB smart contracts wallet runtime"
version.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"

[lib]
name = "rgbp"
crate-type = ["cdylib", "rlib"]

[dependencies]
amplify = { workspace = true }
commit_verify = { workspace = true }
nonasync = { workspace = true }
bp-std = { workspace = true }
bp-wallet = { workspace = true }
rgb-std = { workspace = true, features = ["bitcoin"] }
indexmap = { workspace = true }
serde = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
all = [
    "std",
    "serde", "log", "fs",
]
std = []
fs = [
    "std",
    "serde",
    "rgb-std/fs",
    "bp-wallet/fs",
]
serde = [
    "dep:serde", "serde_yaml",
    "bp-std/serde", "rgb-std/serde"
]

[package.metadata.docs.rs]
features = ["all"]

[patch.crates-io]
ultrasonic = { git = "https://github.com/AluVM/ultrasonic", branch = "refactor/consensus" }
hypersonic = { git = "https://github.com/AluVM/sonic", branch = "refactor/consensus" }
sonic-api = { git = "https://github.com/AluVM/sonic", branch = "refactor/consensus" }
sonic-callreq = { git = "https://github.com/AluVM/sonic", branch = "refactor/consensus" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "refactor/consensus" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "refactor/consensus" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "refactor/consensus" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "refactor/consensus" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "refactor/consensus" }
bp-derive = { git = "https://github.com/BP-WG/bp-std", branch = "refactor/consensus" }
descriptors = { git = "https://github.com/BP-WG/bp-std", branch = "refactor/consensus" }
psbt = { git = "https://github.com/BP-WG/bp-std", branch = "refactor/consensus" }
bp-std = { git = "https://github.com/BP-WG/bp-std", branch = "refactor/consensus" }
bp-wallet = { git = "https://github.com/BP-WG/bp-wallet", branch = "v0.12" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "refactor/consensus" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "refactor/consensus" }
rgb-invoice = { git = "https://github.com/RGB-WG/rgb-std", branch = "refactor/consensus" }
